# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Enviroment Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Cursor
envd = HYPRCURSOR_SIZE,24
envd = XCURSOR_SIZE,24
envd = QT_CURSOR_SIZE,24

# Wayland/Toolkit integration (envd for portal compatibility)
envd = QT_QPA_PLATFORM,wayland;xcb
envd = GDK_BACKEND,wayland,x11,*
envd = XDG_CURRENT_DESKTOP,Hyprland
envd = XDG_SESSION_TYPE,wayland
envd = XDG_SESSION_DESKTOP,Hyprland

# Other
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland
env = AQ_NO_MODIFIERS,1
