# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Input Configuration                    ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Input wiki https://wiki.hyprland.org/0.45.0/Configuring/Variables/#input

input {
    kb_layout = ro,de
    kb_options = grp:shift_caps_toggle
    numlock_by_default = true
    repeat_rate = 50
    repeat_delay = 300
    sensitivity = 1
    accel_profile = adaptive
    scroll_method = 2fg
    follow_mouse = 1
    float_switch_override_focus = 2
}
