# shellcheck shell=bash
# Default layout detection.
# Sourced by scripts/location-switch. Regenerated by scripts/configure.
#
# Ships as a 'single' fallback. Run the wizard (~/.config/hypr/scripts/configure)
# to generate a real detect_location() for your layouts.

detect_location() {
  echo "single"
}
